parameters:
#    jjh_mon_premier.example.class: Jjh\MonPremierBundle\Example

services:
#    jjh_mon_premier.example:
#        class: %jjh_mon_premier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
